[package]
name = "sql_migration"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "migrate"
path = "src/migrate.rs"


[dependencies]
chrono = "0.4.39"
sqlx = { version = "0.8", features = ["runtime-tokio", "postgres"] }
tokio = { version = "1.43.0", features = ["full"] }


