[config]
default_to_workspace = false

[tasks.manage]
description = "Run Django manage.py commands from the Rust project root"
args = ["./table_definition/manage.py", "${@}"]
command = "python"

[tasks.syncdb]
description = "Run syncdb binary"
command = "cargo"
env = { "CARGO_MANIFEST_DIR" = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/webapp" }
args = [
    "run",
    "--package",
    "syncdb"
]

[tasks.generate]
description = "Run npm run generate in the ./front Nuxt.js project"
cwd = "./front"
command = "npm"
args = ["run", "generate"]

[tasks.wasm]
description = "build wasm by wasm-pack(debug build)"
cwd = "./datapack"
command = "wasm-pack"
args = ["build", "--target", "web", "--out-dir", "../front/public/pkg"]

[tasks.wasm-release]
description = "build wasm by wasm-pack(release build)"
cwd = "./datapack"
command = "wasm-pack"
args = ["build", "--release", "--target", "web", "--out-dir", "../front/public/pkg"]

