[config]
cargo-make = true
default_to_workspace = false

[tasks.manage]
description = "Run Django manage.py commands from the Rust project root"
args = ["./table_definition/manage.py", "${@}"]
command = "python"

[tasks.syncdb]
description = "Run syncdb binary with generator-deps feature"
command = "cargo"
env = { "CARGO_MANIFEST_DIR" = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/webapp" }
args = [
    "run",
    "--package",
    "webapp",
    "--bin",
    "syncdb",
    "--features",
    "generator-deps"
]
