# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.synced_folder "./data", "/vagrant_data", "create": true
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = "2"
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    sudo apt-get install -y ansible
  SHELL

#   config.vm.provision "ansible_local" do |ansible|
#     ansible.compatibility_mode = "2.0"
#     ansible.playbook = "/vagrant_data/pgvector.yaml"     # Playbookを指定
#     ansible.inventory_path = "/vagrant_data/hosts.ini"  # インベントリファイルを指定
#     ansible.extra_vars = { ansible_connection: "local", ansible_become: true }
#   end
end
