[package]
name = "datapack"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[[bin]]
name = "extract"
path = "src/extract.rs"

[dependencies]
wasm-bindgen = "0.2"
webapp = { path = "../webapp" }
sqlx = { workspace = true }
tokio = { workspace = true }
dotenvy = { workspace = true }

[profile.release]
lto = "fat"              # リンク時の最適化を有効（ファイルをさらに小さく）
codegen-units = 1        # コード生成を1つのユニットで集中させる。処理速度向上
opt-level = "z"
