# Generated by Django 5.1.6 on 2025-02-26 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('code', models.CharField(max_length=32)),
                ('sort_asc', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'カードタイプ',
                'verbose_name_plural': 'カードタイプ',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('code', models.CharField(max_length=16)),
                ('sort_asc', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '色',
                'verbose_name_plural': '色',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('code', models.CharField(max_length=16)),
                ('sort_asc', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '効果',
                'verbose_name_plural': '効果',
            },
        ),
        migrations.CreateModel(
            name='Klass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat1', models.CharField(max_length=5)),
                ('cat2', models.CharField(blank=True, max_length=5, null=True)),
                ('cat3', models.CharField(blank=True, max_length=5, null=True)),
                ('sort_asc', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '種族',
                'verbose_name_plural': '種族',
            },
        ),
        migrations.CreateModel(
            name='Lrig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('code', models.CharField(max_length=16)),
                ('sort_asc', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'ルリグタイプ',
                'verbose_name_plural': 'ルリグタイプ',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('product_code', models.CharField(max_length=128)),
                ('url', models.URLField(blank=True, null=True)),
                ('product_type', models.CharField(choices=[('bo', 'ブースター'), ('st', 'スターター'), ('pr', 'プロモーション')], max_length=2)),
                ('sort_asc', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '製品',
                'verbose_name_plural': '製品',
            },
        ),
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('code', models.CharField(max_length=16)),
                ('sort_asc', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '使用タイミング',
                'verbose_name_plural': '使用タイミング',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='N/A', max_length=256)),
                ('code', models.CharField(default='N/A', max_length=16)),
                ('pronunciation', models.CharField(default='N/A', max_length=32)),
                ('cost', models.CharField(blank=True, max_length=16, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('limit', models.IntegerField(blank=True, null=True)),
                ('limit_ex', models.IntegerField(blank=True, null=True)),
                ('power', models.CharField(blank=True, max_length=5, null=True)),
                ('has_burst', models.BooleanField(default=False)),
                ('skill_text', models.TextField(blank=True, null=True)),
                ('burst_text', models.TextField(blank=True, null=True)),
                ('format', models.IntegerField(choices=[(1, '(001) ディーヴァセレクション'), (3, '(011) キーセレクション'), (7, '(111) オールスター')], default=0)),
                ('story', models.CharField(blank=True, max_length=16, null=True)),
                ('rarity', models.CharField(blank=True, choices=[('lr', 'LR'), ('lc', 'LC'), ('sr', 'SR'), ('r', 'R'), ('c', 'C'), ('stlr', 'STLR'), ('st', 'ST'), ('pr', 'PR'), ('sp', 'SP'), ('re', 'Re'), ('cb', 'CB'), ('pl', 'Pl'), ('l', 'L')], max_length=8, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('card_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wix.cardtype')),
                ('color', models.ManyToManyField(to='wix.color')),
                ('feature', models.ManyToManyField(blank=True, to='wix.feature')),
                ('klass', models.ManyToManyField(blank=True, to='wix.klass')),
                ('user', models.ManyToManyField(blank=True, to='wix.lrig')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wix.product')),
                ('timing', models.ManyToManyField(blank=True, to='wix.timing')),
            ],
            options={
                'verbose_name': 'カード',
                'verbose_name_plural': 'カード',
            },
        ),
    ]
