# Generated by Django 5.1.6 on 2025-03-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wix', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': '特性', 'verbose_name_plural': '特性'},
        ),
        migrations.AddField(
            model_name='timing',
            name='bit',
            field=models.IntegerField(default=16, verbose_name='ビット値'),
        ),
        migrations.AlterField(
            model_name='card',
            name='burst_text',
            field=models.TextField(blank=True, null=True, verbose_name='テキスト(バースト)'),
        ),
        migrations.AlterField(
            model_name='card',
            name='code',
            field=models.CharField(default='N/A', max_length=16, verbose_name='番号'),
        ),
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.IntegerField(default=128, verbose_name='色'),
        ),
        migrations.AlterField(
            model_name='card',
            name='cost',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='使用コスト'),
        ),
        migrations.AlterField(
            model_name='card',
            name='feature',
            field=models.ManyToManyField(blank=True, to='wix.feature', verbose_name='特性'),
        ),
        migrations.AlterField(
            model_name='card',
            name='format',
            field=models.IntegerField(choices=[(1, '(001) ディーヴァセレクション'), (3, '(011) キーセレクション'), (7, '(111) オールスター')], default=0, verbose_name='フォーマット'),
        ),
        migrations.AlterField(
            model_name='card',
            name='has_burst',
            field=models.BooleanField(default=False, verbose_name='バースト有無'),
        ),
        migrations.AlterField(
            model_name='card',
            name='klass',
            field=models.ManyToManyField(blank=True, to='wix.klass', verbose_name='種族'),
        ),
        migrations.AlterField(
            model_name='card',
            name='level',
            field=models.IntegerField(blank=True, null=True, verbose_name='レベル'),
        ),
        migrations.AlterField(
            model_name='card',
            name='limit',
            field=models.IntegerField(blank=True, null=True, verbose_name='リミット'),
        ),
        migrations.AlterField(
            model_name='card',
            name='limit_ex',
            field=models.IntegerField(blank=True, null=True, verbose_name='リミット消費'),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(default='N/A', max_length=256, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='card',
            name='power',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='パワー'),
        ),
        migrations.AlterField(
            model_name='card',
            name='pronunciation',
            field=models.CharField(default='N/A', max_length=32, verbose_name='読み方'),
        ),
        migrations.AlterField(
            model_name='card',
            name='rarity',
            field=models.CharField(blank=True, choices=[('lr', 'LR'), ('lc', 'LC'), ('sr', 'SR'), ('r', 'R'), ('c', 'C'), ('stlr', 'STLR'), ('st', 'ST'), ('pr', 'PR'), ('sp', 'SP'), ('re', 'Re'), ('cb', 'CB'), ('pl', 'Pl'), ('l', 'L')], max_length=8, null=True, verbose_name='レアリティ'),
        ),
        migrations.AlterField(
            model_name='card',
            name='skill_text',
            field=models.TextField(blank=True, null=True, verbose_name='テキスト'),
        ),
        migrations.AlterField(
            model_name='card',
            name='story',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='ストーリー'),
        ),
        migrations.AlterField(
            model_name='card',
            name='timing',
            field=models.ManyToManyField(blank=True, to='wix.timing', verbose_name='使用タイミング'),
        ),
        migrations.AlterField(
            model_name='card',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='詳細ページ'),
        ),
        migrations.AlterField(
            model_name='card',
            name='user',
            field=models.ManyToManyField(blank=True, to='wix.lrig', verbose_name='限定条件'),
        ),
        migrations.AlterField(
            model_name='cardtype',
            name='code',
            field=models.CharField(max_length=32, verbose_name='内部値'),
        ),
        migrations.AlterField(
            model_name='cardtype',
            name='name',
            field=models.CharField(max_length=8, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='cardtype',
            name='sort_asc',
            field=models.IntegerField(default=0, verbose_name='ソート順(昇順)'),
        ),
        migrations.AlterField(
            model_name='color',
            name='bit',
            field=models.IntegerField(default=128, verbose_name='ビット値'),
        ),
        migrations.AlterField(
            model_name='color',
            name='code',
            field=models.CharField(max_length=16, verbose_name='内部値'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=256, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='color',
            name='sort_asc',
            field=models.IntegerField(default=0, verbose_name='ソート順(昇順)'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='code',
            field=models.CharField(max_length=16, verbose_name='内部値'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=16, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='sort_asc',
            field=models.IntegerField(default=0, verbose_name='ソート順(昇順)'),
        ),
        migrations.AlterField(
            model_name='klass',
            name='cat1',
            field=models.CharField(max_length=5, verbose_name='大分類'),
        ),
        migrations.AlterField(
            model_name='klass',
            name='cat2',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='小分類1'),
        ),
        migrations.AlterField(
            model_name='klass',
            name='cat3',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='小分類2'),
        ),
        migrations.AlterField(
            model_name='klass',
            name='sort_asc',
            field=models.IntegerField(default=0, verbose_name='ソート順(昇順)'),
        ),
        migrations.AlterField(
            model_name='lrig',
            name='code',
            field=models.CharField(max_length=16, verbose_name='内部値'),
        ),
        migrations.AlterField(
            model_name='lrig',
            name='name',
            field=models.CharField(max_length=16, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='lrig',
            name='sort_asc',
            field=models.IntegerField(default=0, verbose_name='ソート順(昇順)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=256, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(max_length=128, verbose_name='商品コード'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('bo', 'ブースター'), ('st', 'スターター'), ('pr', 'プロモーション')], max_length=2, verbose_name='商品タイプ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sort_asc',
            field=models.IntegerField(default=0, verbose_name='ソート順(昇順)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='商品ページ'),
        ),
        migrations.AlterField(
            model_name='timing',
            name='code',
            field=models.CharField(max_length=16, verbose_name='内部値'),
        ),
        migrations.AlterField(
            model_name='timing',
            name='name',
            field=models.CharField(max_length=16, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='timing',
            name='sort_asc',
            field=models.IntegerField(default=0, verbose_name='ソート順(昇順)'),
        ),
    ]
