# Generated by Django 5.1.6 on 2025-02-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='bool1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='option1',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(default='taro', max_length=256),
        ),
    ]
