# Generated by Django 5.1.6 on 2025-03-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wix', '0002_alter_feature_options_timing_bit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='timing',
        ),
        migrations.AddField(
            model_name='card',
            name='timing',
            field=models.IntegerField(default=1, verbose_name='使用タイミング'),
        ),
    ]
