# Generated by Django 5.1.6 on 2025-02-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wix', '0003_tag_card_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='zip_code',
            field=models.CharField(default='813-0041', max_length=10),
        ),
    ]
