# Generated by Django 5.1.6 on 2025-03-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wix', '0003_remove_card_timing_card_timing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='timing',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='使用タイミング'),
        ),
    ]
