# Generated by Django 5.1.6 on 2025-03-05 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wix', '0004_alter_card_timing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.IntegerField(default=0, verbose_name='カード種類'),
        ),
    ]
