# Generated by Django 5.1.6 on 2025-02-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wix', '0004_card_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='tags',
            field=models.ManyToManyField(to='wix.tag'),
        ),
    ]
