# Generated by Django 5.1.6 on 2025-02-13 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wix', '0005_card_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='tags',
            new_name='tagsa',
        ),
    ]
