# Generated by Django 5.1.6 on 2025-03-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wix', '0006_alter_card_has_burst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='product',
            field=models.IntegerField(default=0, verbose_name='収録商品'),
        ),
    ]
