# Generated by Django 5.1.6 on 2025-03-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wix', '0007_alter_card_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='feature_bits1',
            field=models.PositiveBigIntegerField(default=0, verbose_name='効果1群'),
        ),
        migrations.AddField(
            model_name='card',
            name='feature_bits2',
            field=models.PositiveBigIntegerField(default=0, verbose_name='効果2群'),
        ),
    ]
