# Generated by Django 5.1.6 on 2025-03-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wix', '0008_card_feature_bits1_card_feature_bits2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='feature_bits1',
            field=models.BigIntegerField(default=0, verbose_name='効果1群'),
        ),
        migrations.AlterField(
            model_name='card',
            name='feature_bits2',
            field=models.BigIntegerField(default=0, verbose_name='効果2群'),
        ),
    ]
