# Generated by Django 5.2.1 on 2025-06-09 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wix', '0011_alter_product_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(db_index=True, max_length=20, verbose_name='カード番号')),
                ('name', models.CharField(max_length=200, verbose_name='カード名')),
                ('raw_html', models.TextField(verbose_name='生HTML')),
                ('skill_text', models.TextField(blank=True, help_text='cardSkillセクションのテキスト', verbose_name='スキルテキスト')),
                ('life_burst_text', models.TextField(blank=True, help_text='ライフバースト部分のテキスト', verbose_name='ライフバーストテキスト')),
                ('source_url', models.URLField(max_length=500, verbose_name='ソースURL')),
                ('scraped_at', models.DateTimeField(auto_now_add=True, verbose_name='スクレイピング日時')),
                ('last_analyzed_at', models.DateTimeField(blank=True, null=True, verbose_name='最終解析日時')),
                ('is_analyzed', models.BooleanField(default=False, verbose_name='解析済み')),
                ('analysis_error', models.TextField(blank=True, verbose_name='解析エラー')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_cards', to='wix.product', verbose_name='収録商品')),
            ],
            options={
                'verbose_name': '生カードデータ',
                'verbose_name_plural': '生カードデータ',
                'ordering': ['product', 'card_number'],
                'indexes': [models.Index(fields=['card_number'], name='wix_rawcard_card_nu_3a5e4d_idx'), models.Index(fields=['scraped_at'], name='wix_rawcard_scraped_d31a6b_idx'), models.Index(fields=['is_analyzed'], name='wix_rawcard_is_anal_aca978_idx')],
                'unique_together': {('card_number', 'product')},
            },
        ),
    ]
