# Generated by Django 5.2.1 on 2025-06-09 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wix', '0012_rawcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawcard',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raw_cards', to='wix.product', verbose_name='収録商品'),
        ),
    ]
