# Generated by Django 5.2.1 on 2025-06-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wix', '0013_alter_rawcard_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawcard',
            name='card_number',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='カード番号'),
        ),
    ]
