# Generated by Django 5.2.1 on 2025-06-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wix', '0014_alter_rawcard_card_number'),
    ]

    operations = [
        # RawCardテーブルを再作成（unique制約付き）
        migrations.RunSQL(
            "CREATE TABLE IF NOT EXISTS wix_rawcard ("
            "id BIGSERIAL PRIMARY KEY, "
            "card_number VARCHAR(20) UNIQUE NOT NULL, "
            "name VARCHAR(200) NOT NULL, "
            "product_id BIGINT REFERENCES wix_product(id) ON DELETE CASCADE, "
            "raw_html TEXT NOT NULL, "
            "skill_text TEXT NOT NULL DEFAULT '', "
            "life_burst_text TEXT NOT NULL DEFAULT '', "
            "source_url VARCHAR(500) NOT NULL, "
            "scraped_at TIMESTAMPTZ NOT NULL, "
            "last_analyzed_at TIMESTAMPTZ, "
            "is_analyzed BOOLEAN NOT NULL DEFAULT FALSE, "
            "analysis_error TEXT NOT NULL DEFAULT ''"
            ");",
            reverse_sql="DROP TABLE IF EXISTS wix_rawcard;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS wix_rawcard_card_number_idx ON wix_rawcard(card_number);",
            reverse_sql="DROP INDEX IF EXISTS wix_rawcard_card_number_idx;"
        ),
    ]