# Generated by Django 5.2.1 on 2025-06-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wix', '0015_auto_20250609_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='pronunciation',
            field=models.CharField(default='N/A', max_length=64, verbose_name='読み方'),
        ),
    ]
