# Generated by Django 5.2.2 on 2025-06-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wix', '0016_alter_card_pronunciation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='code',
            field=models.CharField(default='N/A', max_length=16, unique=True, verbose_name='番号'),
        ),
    ]
