# Generated by Django 5.2.2 on 2025-06-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wix', '0017_alter_card_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='pronunciation',
            field=models.CharField(default='N/A', max_length=128, verbose_name='読み方'),
        ),
    ]
