# Generated by Django 5.2.1 on 2025-06-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wix', '0019_create_rule_pattern_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardtype',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='デフォルト表示するカードタイプかどうか', verbose_name='主要カードタイプ'),
        ),
        migrations.AlterField(
            model_name='rulepattern',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
