# Generated by Django 5.2.1 on 2025-06-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wix', '0020_cardtype_is_primary_alter_rulepattern_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='burst_bits',
            field=models.BigIntegerField(default=0, verbose_name='ライフバースト効果'),
        ),
    ]
