# Generated by Django 5.2.1 on 2025-06-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wix', '0021_card_burst_bits'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardFeatureOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pronunciation', models.CharField(db_index=True, help_text='同じ読み方のカードは全て同じフィーチャーが適用されます', max_length=200, unique=True, verbose_name='読み方')),
                ('fixed_bits1', models.BigIntegerField(help_text='手動で修正されたCardFeatureのビット値（1群）', verbose_name='修正済み効果1群')),
                ('fixed_bits2', models.BigIntegerField(help_text='手動で修正されたCardFeatureのビット値（2群）', verbose_name='修正済み効果2群')),
                ('fixed_burst_bits', models.BigIntegerField(help_text='手動で修正されたBurstFeatureのビット値', verbose_name='修正済みライフバースト効果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('note', models.TextField(blank=True, help_text='修正理由や特記事項', verbose_name='メモ')),
            ],
            options={
                'verbose_name': 'カードフィーチャー修正',
                'verbose_name_plural': 'カードフィーチャー修正',
                'db_table': 'wix_card_feature_override',
                'ordering': ['pronunciation'],
            },
        ),
    ]
