[package]
name = "analyzer"
version = "0.1.0"
edition = "2024"

[lib]
name = "analyzer"
path = "src/lib.rs"

[dependencies]
regex = { workspace = true }
feature = { path = "../shared/feature" }
rayon = "1.10"
once_cell = "1.20"
