[package]
name = "sqlm"
version = "0.1.0"
edition = "2021"
build = "build.rs"


[dependencies]
chrono = "0.4.39"
rustpython-parser = "0.4.0"
rustpython-parser-core = "0.4.0"
sqlx = { version = "0.8", features = ["runtime-tokio", "postgres"] }
tokio = { version = "1.43.0", features = ["full"] }

[build-dependencies]
rustpython-parser = "0.4.0"
rustpython-parser-core = "0.4.0"
