[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = ["-c", "if [ ! -f ../datapack/src/gen/cards.rs ]; then echo 'Error: ../datapack/src/gen/cards.rs not found. Run cargo make static first.'; exit 1; fi"]

[[hooks]]
stage = "post_build"
command = "sh"
command_arguments = ["-c", "touch ../dist-pages/.nojekyll && cp ../gh-pages-404.html ../dist-pages/404.html"]

[build]
target = "index.html"
dist = "../dist-pages"
public_url = "/django_bridge/"
release = true
