cargo run --release --example scrape booster WXDi-P01
cargo run --release --example scrape booster WXDi-P02
cargo run --release --example scrape booster WXDi-P03
cargo run --release --example scrape booster WXDi-P04
cargo run --release --example scrape booster WXDi-P05
cargo run --release --example scrape booster WXDi-P00
cargo run --release --example scrape booster WXDi-P06
cargo run --release --example scrape booster WXDi-P07
cargo run --release --example scrape booster WXDi-P08
cargo run --release --example scrape booster WXDi-P09
cargo run --release --example scrape booster WXDi-P10
cargo run --release --example scrape booster WXDi-P11
cargo run --release --example scrape booster WXDi-CP01
cargo run --release --example scrape booster WXDi-P12
cargo run --release --example scrape booster WXDi-P13
cargo run --release --example scrape booster WXDi-P14
cargo run --release --example scrape booster WXDi-CP02
cargo run --release --example scrape booster WXDi-P15
cargo run --release --example scrape booster WXDi-P16
cargo run --release --example scrape booster WX24-P1
cargo run --release --example scrape booster WX24-P2
cargo run --release --example scrape booster WX24-P3
cargo run --release --example scrape booster WX24-P4
