# Generated by Django 5.2.1 on 2025-06-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='設定の識別キー（例: admin_root, maintenance_mode）', max_length=100, unique=True, verbose_name='設定キー')),
                ('value', models.TextField(blank=True, help_text='設定の値（文字列、JSON等）', verbose_name='設定値')),
                ('description', models.CharField(blank=True, help_text='この設定の説明', max_length=255, verbose_name='説明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'サイト設定',
                'verbose_name_plural': 'サイト設定',
                'ordering': ['key'],
            },
        ),
    ]
