[package]
name = "models"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
sqlx = { workspace = true }
chrono = { workspace = true }
icon_encoder = { path = "../../icon_encoder" }